"""
utils/export.py - PDF and DOCX export utilities.

Dependencies (add to requirements.txt):
    weasyprint>=61.0
    python-docx>=1.1.0
"""

import logging
import io
import re
from datetime import datetime

logger = logging.getLogger(__name__)



# ------------------------------------------------------------------ #
# HTML → PDF                                                          #
# ------------------------------------------------------------------ #

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import inch
import io
from datetime import datetime


def report_to_pdf(startup: dict, report: dict) -> bytes:
    """
    Generate Startup Analysis PDF using ReportLab.
    """

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph(
            f"<b><font size=20>{startup.get('startup_name','Startup Analysis')}</font></b>",
            styles["Title"],
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            f"<b>Founder:</b> {startup.get('founder_name','')}",
            styles["Normal"],
        )
    )

    story.append(
        Paragraph(
            f"<b>Industry:</b> {startup.get('industry','')}",
            styles["Normal"],
        )
    )

    story.append(
        Paragraph(
            f"<b>Country:</b> {startup.get('country','')}",
            styles["Normal"],
        )
    )

    story.append(
        Paragraph(
            f"<b>Budget:</b> {startup.get('budget','')}",
            styles["Normal"],
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    story.append(Paragraph("<b>AI Analysis Scores</b>", styles["Heading2"]))

    story.append(
        Paragraph(
            f"Viability: {report.get('viability_score',0)}%",
            styles["Normal"],
        )
    )

    story.append(
        Paragraph(
            f"Market: {report.get('market_score',0)}%",
            styles["Normal"],
        )
    )

    story.append(
        Paragraph(
            f"Innovation: {report.get('innovation_score',0)}%",
            styles["Normal"],
        )
    )

    story.append(
        Paragraph(
            f"Execution: {report.get('execution_score',0)}%",
            styles["Normal"],
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph("<b>Startup Analysis</b>", styles["Heading2"])
    )

    content = report.get("content", "")

    for line in content.split("\n"):

        line = line.strip()

        if not line:
            continue

        story.append(
            Paragraph(line.replace("\n", "<br/>"), styles["BodyText"])
        )

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph("<b>Original Idea</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(startup.get("idea_description", ""), styles["BodyText"])
    )

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            f"Generated by AI Startup Incubator Agent<br/>{datetime.now()}",
            styles["Italic"],
        )
    )

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf
    """
    Render a startup analysis report as a PDF and return raw bytes.
    Uses WeasyPrint (HTML → PDF pipeline).
    """
    try:
        from weasyprint import HTML, CSS  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "WeasyPrint is not installed. Run: pip install weasyprint"
        ) from exc

    html_str = _build_report_html(startup, report)
    try:
        pdf_bytes = HTML(string=html_str, base_url=None).write_pdf()
        return pdf_bytes
    except Exception as exc:
        logger.error("PDF generation failed: %s", exc)
        raise RuntimeError(f"PDF generation failed: {exc}") from exc





def incubation_report_to_pdf(report: dict) -> bytes:

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph(
            f"<b><font size=20>Incubation Report</font></b>",
            styles["Title"],
        )
    )

    story.append(
        Paragraph(
            f"<b>Startup:</b> {report.get('startup_name','')}",
            styles["Normal"],
        )
    )

    story.append(
        Paragraph(
            f"<b>Founder:</b> {report.get('founder_name','')}",
            styles["Normal"],
        )
    )

    story.append(
        Paragraph(
            f"<b>Industry:</b> {report.get('industry','')}",
            styles["Normal"],
        )
    )

    story.append(
        Paragraph(
            f"<b>Validation Score:</b> {report.get('validation_score',0)}%",
            styles["Normal"],
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    SECTION_TITLES = {
        "EXECUTIVE_SUMMARY": "Executive Summary",
        "PROBLEM_ANALYSIS": "Problem Analysis",
        "SOLUTION": "Solution",
        "CUSTOMER_PERSONAS": "Customer Personas",
        "MARKET_RESEARCH": "Market Research",
        "COMPETITOR_ANALYSIS": "Competitor Analysis",
        "SWOT_ANALYSIS": "SWOT Analysis",
        "BUSINESS_MODEL_CANVAS": "Business Model Canvas",
        "REVENUE_MODEL": "Revenue Model",
        "PRICING_STRATEGY": "Pricing Strategy",
        "ESTIMATED_BUDGET": "Estimated Budget",
        "FUNDING_SUGGESTIONS": "Funding Suggestions",
        "GOVERNMENT_SCHEMES": "Government Schemes",
        "LEGAL_CHECKLIST": "Legal Checklist",
        "TECHNOLOGY_RECOMMENDATION": "Technology Recommendation",
        "DEVELOPMENT_ROADMAP": "Development Roadmap",
        "WEEKLY_TIMELINE": "Weekly Timeline",
        "MARKETING_STRATEGY": "Marketing Strategy",
        "CUSTOMER_ACQUISITION_PLAN": "Customer Acquisition Plan",
        "INVESTOR_PITCH": "Investor Pitch",
        "RISK_ANALYSIS": "Risk Analysis",
        "SUCCESS_METRICS": "Success Metrics",
        "MENTOR_ADVICE": "Mentor Advice",
    }

    sections = report.get("sections", {})

    for key, title in SECTION_TITLES.items():

        if key not in sections:
            continue

        story.append(Paragraph(f"<b>{title}</b>", styles["Heading2"]))

        text = sections[key]

        for line in text.split("\n"):

            line = line.strip()

            if line:

                story.append(
                    Paragraph(line, styles["BodyText"])
                )

        story.append(Spacer(1, 0.15 * inch))

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            f"Generated by AI Startup Incubator Agent<br/>{datetime.now()}",
            styles["Italic"],
        )
    )

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf

# ------------------------------------------------------------------ #
# Report → DOCX                                                       #
# ------------------------------------------------------------------ #

def report_to_docx(startup: dict, report: dict) -> bytes:
    """Generate a DOCX document from a startup analysis report."""
    try:
        from docx import Document  # type: ignore
        from docx.shared import Pt, RGBColor  # type: ignore
        from docx.enum.text import WD_ALIGN_PARAGRAPH  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "python-docx is not installed. Run: pip install python-docx"
        ) from exc

    doc = Document()

    # Title
    title_para = doc.add_heading(startup.get("startup_name", "Startup Analysis"), 0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Meta info table
    doc.add_heading("Startup Overview", level=1)
    table = doc.add_table(rows=1, cols=2)
    table.style = "Light Grid Accent 1"
    meta_fields = [
        ("Founder", startup.get("founder_name", "")),
        ("Industry", startup.get("industry", "")),
        ("Country", startup.get("country", "")),
        ("Budget", startup.get("budget", "")),
        ("Status", startup.get("status", "").title()),
        ("Created", startup.get("created_at", "")),
    ]
    hdr = table.rows[0].cells
    hdr[0].text = "Field"
    hdr[1].text = "Value"
    for field, value in meta_fields:
        row = table.add_row()
        row.cells[0].text = field
        row.cells[1].text = str(value)

    doc.add_paragraph()

    # Scores
    if report:
        doc.add_heading("AI Scores", level=1)
        scores_table = doc.add_table(rows=1, cols=2)
        scores_table.style = "Light Grid Accent 1"
        sh = scores_table.rows[0].cells
        sh[0].text = "Dimension"
        sh[1].text = "Score"
        for dim, key in [
            ("Viability", "viability_score"),
            ("Market Fit", "market_score"),
            ("Innovation", "innovation_score"),
            ("Execution", "execution_score"),
        ]:
            row = scores_table.add_row()
            row.cells[0].text = dim
            row.cells[1].text = f"{report.get(key, 0)}%"
        doc.add_paragraph()

        # Full report content
        doc.add_heading("Full Analysis Report", level=1)
        content = report.get("content", "")
        _add_markdown_content(doc, content)

    # Idea description
    doc.add_heading("Original Idea Description", level=1)
    doc.add_paragraph(startup.get("idea_description", ""))

    doc.add_paragraph()
    footer_para = doc.add_paragraph(
        f"Generated by AI Startup Incubator Agent | {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    )
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


def incubation_report_to_docx(report: dict) -> bytes:
    """Generate a DOCX document from a full incubation (mentor) report."""
    try:
        from docx import Document  # type: ignore
        from docx.shared import Pt  # type: ignore
        from docx.enum.text import WD_ALIGN_PARAGRAPH  # type: ignore
    except ImportError as exc:
        raise RuntimeError("python-docx is not installed. Run: pip install python-docx") from exc

    doc = Document()

    # Title
    title = doc.add_heading(f"Incubation Report: {report.get('startup_name', '')}", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    sub = doc.add_paragraph(
        f"Founder: {report.get('founder_name', '')}  |  "
        f"Industry: {report.get('industry', '')}  |  "
        f"Country: {report.get('country', '')}  |  "
        f"Validation Score: {report.get('validation_score', 0)}%"
    )
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph()

    SECTION_TITLES = {
        "EXECUTIVE_SUMMARY":         "Executive Summary",
        "PROBLEM_ANALYSIS":          "Problem Analysis",
        "SOLUTION":                  "Solution",
        "CUSTOMER_PERSONAS":         "Customer Personas",
        "MARKET_RESEARCH":           "Market Research",
        "COMPETITOR_ANALYSIS":       "Competitor Analysis",
        "SWOT_ANALYSIS":             "SWOT Analysis",
        "BUSINESS_MODEL_CANVAS":     "Business Model Canvas",
        "REVENUE_MODEL":             "Revenue Model",
        "PRICING_STRATEGY":          "Pricing Strategy",
        "ESTIMATED_BUDGET":          "Estimated Budget",
        "FUNDING_SUGGESTIONS":       "Funding Suggestions",
        "GOVERNMENT_SCHEMES":        "Government Schemes",
        "LEGAL_CHECKLIST":           "Legal Checklist",
        "TECHNOLOGY_RECOMMENDATION": "Technology Recommendation",
        "DEVELOPMENT_ROADMAP":       "Development Roadmap",
        "WEEKLY_TIMELINE":           "Weekly Timeline",
        "MARKETING_STRATEGY":        "Marketing Strategy",
        "CUSTOMER_ACQUISITION_PLAN": "Customer Acquisition Plan",
        "INVESTOR_PITCH":            "Investor Pitch",
        "RISK_ANALYSIS":             "Risk Analysis",
        "SUCCESS_METRICS":           "Success Metrics",
        "MENTOR_ADVICE":             "Personalized Mentor Advice",
    }

    sections = report.get("sections", {})
    for key, title in SECTION_TITLES.items():
        content = sections.get(key, "")
        if not content:
            continue
        doc.add_heading(title, level=1)
        _add_markdown_content(doc, content)
        doc.add_paragraph()

    doc.add_paragraph()
    footer = doc.add_paragraph(
        f"Generated by AI Startup Incubator Agent | {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    )
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


# ------------------------------------------------------------------ #
# Internal helpers                                                    #
# ------------------------------------------------------------------ #

def _add_markdown_content(doc, text: str) -> None:
    """Add basic markdown-like text to a DOCX document."""
    if not text:
        return
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("## "):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith("### "):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith(("- ", "* ", "• ")):
            para = doc.add_paragraph(stripped[2:], style="List Bullet")
        elif stripped:
            # Bold markers
            para = doc.add_paragraph()
            parts = re.split(r"\*\*(.+?)\*\*", stripped)
            for i, part in enumerate(parts):
                run = para.add_run(part)
                if i % 2 == 1:
                    run.bold = True


CSS_EXPORT = """
body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 12pt;
       color: #1a1a2e; line-height: 1.6; margin: 0; padding: 0; }
.page { max-width: 800px; margin: 0 auto; padding: 40px; }
h1 { font-size: 24pt; color: #1a1a2e; border-bottom: 2px solid #3b82d4; padding-bottom: 8px; }
h2 { font-size: 16pt; color: #3b82d4; margin-top: 24px; }
h3 { font-size: 13pt; color: #444; }
table { width: 100%; border-collapse: collapse; margin: 12px 0; }
th { background: #3b82d4; color: white; padding: 8px 12px; text-align: left; }
td { padding: 7px 12px; border-bottom: 1px solid #e5e7eb; }
tr:nth-child(even) td { background: #f7f8fa; }
.score-badge { display: inline-block; background: #3b82d4; color: white;
               padding: 2px 10px; border-radius: 20px; font-weight: bold; }
.meta-row { display: flex; gap: 20px; flex-wrap: wrap; margin: 12px 0; font-size: 11pt; }
.meta-item { color: #555; }
.meta-item strong { color: #1a1a2e; }
.footer { margin-top: 40px; border-top: 1px solid #e5e7eb;
          padding-top: 12px; font-size: 10pt; color: #888; text-align: center; }
ul { padding-left: 20px; }
li { margin-bottom: 4px; }
p { margin: 6px 0; }
"""


def _build_report_html(startup: dict, report: dict) -> str:
    content = report.get("content", "") if report else ""
    # Convert basic markdown
    content = re.sub(r"^## (.+)$", r"<h2>\1</h2>", content, flags=re.MULTILINE)
    content = re.sub(r"^### (.+)$", r"<h3>\1</h3>", content, flags=re.MULTILINE)
    content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
    content = re.sub(r"^\s*[-*] (.+)$", r"<li>\1</li>", content, flags=re.MULTILINE)
    content = content.replace("\n\n", "</p><p>")

    scores_html = ""
    if report:
        scores_html = f"""
        <h2>AI Analysis Scores</h2>
        <table>
          <tr><th>Dimension</th><th>Score</th></tr>
          <tr><td>Viability</td><td><span class="score-badge">{report.get('viability_score', 0)}%</span></td></tr>
          <tr><td>Market Fit</td><td><span class="score-badge">{report.get('market_score', 0)}%</span></td></tr>
          <tr><td>Innovation</td><td><span class="score-badge">{report.get('innovation_score', 0)}%</span></td></tr>
          <tr><td>Execution</td><td><span class="score-badge">{report.get('execution_score', 0)}%</span></td></tr>
        </table>
        """

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"/>
<style>{CSS_EXPORT}</style>
</head><body><div class="page">
<h1>{startup.get('startup_name', 'Startup Analysis')}</h1>
<div class="meta-row">
  <span class="meta-item"><strong>Founder:</strong> {startup.get('founder_name', '')}</span>
  <span class="meta-item"><strong>Industry:</strong> {startup.get('industry', '')}</span>
  <span class="meta-item"><strong>Country:</strong> {startup.get('country', '')}</span>
  <span class="meta-item"><strong>Budget:</strong> {startup.get('budget', '')}</span>
</div>
{scores_html}
<h2>Full Analysis Report</h2>
<p>{content}</p>
<h2>Original Idea Description</h2>
<p>{startup.get('idea_description', '')}</p>
<div class="footer">Generated by AI Startup Incubator Agent &bull;
{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</div>
</div></body></html>"""


def _build_incubation_html(report: dict) -> str:
    sections = report.get("sections", {})
    sections_html = ""
    SECTION_TITLES = {
        "EXECUTIVE_SUMMARY": "Executive Summary",
        "PROBLEM_ANALYSIS": "Problem Analysis",
        "SOLUTION": "Solution",
        "CUSTOMER_PERSONAS": "Customer Personas",
        "MARKET_RESEARCH": "Market Research",
        "COMPETITOR_ANALYSIS": "Competitor Analysis",
        "SWOT_ANALYSIS": "SWOT Analysis",
        "BUSINESS_MODEL_CANVAS": "Business Model Canvas",
        "REVENUE_MODEL": "Revenue Model",
        "PRICING_STRATEGY": "Pricing Strategy",
        "ESTIMATED_BUDGET": "Estimated Budget",
        "FUNDING_SUGGESTIONS": "Funding Suggestions",
        "GOVERNMENT_SCHEMES": "Government Schemes",
        "LEGAL_CHECKLIST": "Legal Checklist",
        "TECHNOLOGY_RECOMMENDATION": "Technology Recommendation",
        "DEVELOPMENT_ROADMAP": "Development Roadmap",
        "WEEKLY_TIMELINE": "Weekly Timeline",
        "MARKETING_STRATEGY": "Marketing Strategy",
        "CUSTOMER_ACQUISITION_PLAN": "Customer Acquisition Plan",
        "INVESTOR_PITCH": "Investor Pitch",
        "RISK_ANALYSIS": "Risk Analysis",
        "SUCCESS_METRICS": "Success Metrics",
        "MENTOR_ADVICE": "Personalized Mentor Advice",
    }
    for key, title in SECTION_TITLES.items():
        content = sections.get(key, "")
        if not content:
            continue
        content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
        content = re.sub(r"^\s*[-*] (.+)$", r"<li>\1</li>", content, flags=re.MULTILINE)
        content = content.replace("\n\n", "</p><p>")
        sections_html += f"<h2>{title}</h2><p>{content}</p>"

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"/>
<style>{CSS_EXPORT}</style>
</head><body><div class="page">
<h1>Incubation Report: {report.get('startup_name', '')}</h1>
<div class="meta-row">
  <span class="meta-item"><strong>Founder:</strong> {report.get('founder_name', '')}</span>
  <span class="meta-item"><strong>Industry:</strong> {report.get('industry', '')}</span>
  <span class="meta-item"><strong>Country:</strong> {report.get('country', '')}</span>
  <span class="meta-item"><strong>Budget:</strong> {report.get('budget', '')}</span>
  <span class="meta-item"><strong>Validation Score:</strong>
    <span class="score-badge">{report.get('validation_score', 0)}%</span></span>
</div>
{sections_html}
<div class="footer">Generated by AI Startup Incubator Agent &bull;
{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</div>
</div></body></html>"""
